### ISSUE TITLE
Auth strategies in payload CMS is not allowed

### ISSUE THREAD

**Issue by stachura93** [WilsonLe/payload-oauth2#14]
Hi,
in latest version of Payload and Node 20.9.0 I've received a bug on User collection. The Auth Strategies is not recognised by Payload.

Step to reproduce:

1.  npx create-payload-app@latest -> payload-demo -> postgresSql
2. copy .env.example and set Database URL connection
3.  and plugin with yarn add (wrong dock on Readme)
4. Config as plugin base on Readme file

In Result:

 Error [ERR_REQUIRE_ESM]: require() of ES Module

Use dynamic import:

1.  yarn add fix-esm
2. add "const payload = require("fix-esm").require("payload-oauth2")"

Run application:

[18:44:44] ERROR (payload): There were 1 errors validating your Payload config
[18:44:44] ERROR (payload): 1: Collection "users" > "auth.strategies[0]" does not match any of the allowed types
[nodemon] app crashed - waiting for file changes before starting...

**Comment by BlainMaguire** [comment]
Hi, I don't think this plugin supports Payload 2 given that Payload 3 is basically a rewrite using Next.js.
Given you seem to be creating a new project, give Payload ```3.0.0-beta.110``` and the latest version of the plugin a try.

**Comment by WilsonLe** [comment]
Yes this plugin does not support Payload v2. This plugin was written because the one I was using for Payload v2 is not compatible with Payload V3. If you don't want to transition to v3 beta (understandably so), give the original inspiration of this plugin a try https://github.com/thgh/payload-plugin-oauth

**Comment by stachura93** [comment]
yea, my gap. I was missed that library is for Beta version of Payload. I thought than will support newest-latest version. Anyway thanks, I've try with Beta and works like a charm.

Closed the Issue
