### ISSUE TITLE
Does not seem to work with beta.112+

### ISSUE THREAD

**Issue by genox** [WilsonLe/payload-oauth2#16]
Hi,

I am currently running the plugin on beta.111 which seems to be the last version that is compatible with this plugin. I assume one of the breaking changes regarding the authentication workflow/config needs to be taken into consideration.

Essentially, I get a redirect to the error page I defined on trying to login using an oauth provider (after being redirected back to my payload instance) - no further error messages are visible in the logs. I saw someone already posted this issue but closed it again, marking it as resolved - I don't think that this is the case.

Unfortunately I can't provide any more debug information since there is none visible. Let me know if I can do anything to change that to contribute to resolving this issue.

Thank you!

edit: typo

**Comment by WilsonLe** [comment]
Have you tried v114? @MatthiasGrandl just said it is fixed in latest beta 20 hours ago: https://github.com/WilsonLe/payload-oauth2/issues/11#issuecomment-2416470874

**Comment by MatthiasGrandl** [comment]
Jup I can confirm this sounds like my issue in #11 and it has been fixed upstream. I am running beta v115 currently.

**Comment by WilsonLe** [comment]
I'm in the midst of writing integration tests with as much oauth providers as I can, sorry if I'm not catching up with payload beta 🥲

**Comment by genox** [comment]
I tried with 114 and 115 just now, including cleaning caches and nuking node_modules etc. - I get redirected to my custom auth error page.

Here is my config, maybe something changed meanwhile:

```
    OAuth2Plugin({
      strategyName: 'oauth2',
      useEmailAsIdentity: false,
      enabled: true,
      serverURL: process.env.NEXT_PUBLIC_URL || 'http://localhost:3000',
      authCollection: Users.slug,
      clientId: process.env.OAUTH_CLIENT_ID || '',
      clientSecret: process.env.OAUTH_CLIENT_SECRET || '',
      tokenEndpoint: 'xxxxxxxx',
      scopes: ['email', 'profile', 'openid'],
      providerAuthorizationUrl: 'xxxxxxxx',
      getUserInfo: async (accessToken) => {
        try {
          const response = await fetch('xxxxxxxx', {
            headers: { Authorization: `Bearer ${accessToken}` },
          });
          const user = await response.json();
          return {
            email: user.email,
            sub: user.sub,
          };
        } catch (error) {
          console.error(error);
          return null;
        }
      },
      successRedirect: () => {
        console.log('Login successful, redirecting to /admin');
        return '/admin';
      },
      failureRedirect: (req, error) => {
        console.error(error);
        return '/oauth-error';
      },
    }),

```

Anything looking suspicious in the above? But things work right now on beta.111 - so there can't be anything fundamentally wrong.

**Comment by WilsonLe** [comment]
what's the output of the `console.error(error)` in your `failureRedirect`?

**Comment by genox** [comment]
Ah - apologies, there's some debug spam in the logs and I didn't catch this at first:

```
TypeError: Cannot read properties of undefined (reading 'cookies')
      at generatePayloadCookie (webpack-internal:///(rsc)/./node_modules/payload/dist/auth/cookies.js:74:50)
      at Object.handler (webpack-internal:///(rsc)/./node_modules/payload-oauth2/dist/callback-endpoint.js:148:90)
....

```

**Comment by MatthiasGrandl** [comment]
Yes this is the same error, which has been fixed in Payload. You probably haven't updated payload properly.

**Comment by genox** [comment]
There is not much more that I can do other than nuking node_modules and the lock file and reinstalling dependencies.. but yes, in this case this seems to be not an issue of this plugin then and specific to my environment. Closing.

**Comment by genox** [comment]
Does not change anything. Just out of curiosity, if you run this plugin on current beta.115 with a generic oauth provider (gitlab ce in my case), does it work for you, @WilsonLe ?

**Comment by MatthiasGrandl** [comment]
@genox appologies, it's definitely still broken. guess it was me who didn't prune his cache properly 🤦‍♂️

**Comment by MatthiasGrandl** [comment]
@genox #13 works for me
