### ISSUE TITLE
v1.0.4 broke exports

### ISSUE THREAD

**Issue by MatthiasGrandl** [WilsonLe/payload-oauth2#17]
in 1.0.3 you would import the plugin with `import { OAuth2Plugin } from "payload-oauth2";`

In 1.04 you have to `import { OAuth2Plugin } from "payload-oauth2/dist/src";` due to changes how the plugin is published.

**Comment by WilsonLe** [comment]
Published v1.0.5 fixing this.

**Comment by MatthiasGrandl** [comment]
Can confirm, it’s fixed!
