### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by markusahrweileramcon** [WilsonLe/payload-oauth2#22]
In callback-endpoint you are using `jsonwebtoken` which is an external dependency but is not defined as a dependency.
Also payload is now released, so you can change the version from beta to 3.0.0

**Comment by WilsonLe** [comment]
Yup, payload@v3 now uses `jose` instead of `jsonwebtoken` as their operations on jwts. I'll update `jose` as the peer deps of `payload` and we should still be using 0 external dependencies.

**Comment by smoove** [comment]
@WilsonLe Hey, nice work on this plugin!
I see you already have the branch for the stable v3, when can we expect this to be released?

**Comment by WilsonLe** [comment]
v1.0.7 is out
