### ISSUE TITLE
Getting 404 page on newer versions of Payload v3 beta

### ISSUE THREAD

**Issue by BlainMaguire** [WilsonLe/payload-oauth2#5]
The OAuth2 flow calls look okay, return codes are expected.
It's when the success redirect tries to take the user to the ```/admin``` route it gives a 404:

Logs:
![image](https://github.com/user-attachments/assets/030688e8-19a2-4e1c-b205-22e4509d3323)

Browser Console:
![image](https://github.com/user-attachments/assets/11547ebd-e369-479b-8c10-e20f5f14a1ba)

Regular logins (not via OAuth2 flow but using email and password on ```/admin/login/``` are working with the plugin enabled).

With users that have completed the OAuth2 flow I can visit ```/api/users``` in the browser and see the user json, and if I clear the cookies such a collection is then forbidden.

There's not much to go by in the logs. Let me know if there's any way I can provide you with additional information.

Next.js: 15.0.0-canary.104
Node.js: v22.2.0
PayloadCMS: 3.0.0-beta.99

**Comment by WilsonLe** [comment]
@BlainMaguire can you confirm if this goes away in v1.0.1? I encounted this and implemented a fix. I had 2 different user collections, one for my client-facing app and 1 for the admin panel. Logging in to client-facing collection gives me 404 on admin panel.

**Comment by BlainMaguire** [comment]
Yes, I can confirm it's working for me now with version ```v1.0.1``` of the plugin and payload ```3.0.0-beta.107```.

Thanks for fixing the issue! I'll close this.
