### ISSUE TITLE
yarn generate:types fails after upgrading to 1.0.2

### ISSUE THREAD

**Issue by BlainMaguire** [WilsonLe/payload-oauth2#9]
Regular ```yarn dev``` doesn't get this error.

Running ```yarn generate:types``` I get:

```bash
file:///home/blain/js/payloadcms-backend/node_modules/payload-oauth2/dist/auth-strategy.js?tsx-namespace=1727890648433:2
import jwt, { TokenExpiredError } from "jsonwebtoken";
              ^^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'jsonwebtoken' does not provide an export named 'TokenExpiredError'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:171:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:254:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:475:24)
    at bin (/home/blain/js/payloadcms-backend/node_modules/payload/dist/bin/index.js:45:27)
    at async start (file:///home/blain/js/payloadcms-backend/node_modules/payload/bin.js:30:7)
```
I also get the same error for: ```yarn generate:importmap```. I'm on payload ```3.0.0-beta.110```.  When I downgrade to ```1.0.1``` the error goes away.

I thought the problem might be my ```tsconfig```, but I have options like this set:
```
    "esModuleInterop": true,
```
If I change the code in the plugin to this:
```const { TokenExpiredError } = jwt;```

It makes the error go away (and I can go through the flow successfully). Also it handles expiry gracefully (I get back to the login screen for OAuth users). Please let me know if the above change is needed or if there's something I need to set in my ```tsconfig```.

**Comment by WilsonLe** [comment]
Fixed in v1.0.3
